### PR TITLE
Update object-assign to 4.0

### PR DESCRIPTION
**Pull request by danez**
4.0 improved the performance a lot, and the ordering might change a bit, but by looking at the code, I think the order is not important for react-themable.

https://github.com/sindresorhus/object-assign/releases

@markdalgleish

### CODE REVIEW

**Comment by theobat** [comment]
It would be great to merge this !

**Comment by thibaudcolas** [comment]
Considering support for ES6 `Object.assign` is quite good (everything except Node v4 and below, IE11 and below), I'd even suggest dropping that dependency and instead simply mention in the README that people who want to support IE will need to polyfill.

It's not a big deal either way, but right now with the outdated dependency it makes it more tempting than it should be to inline the code.

**Comment by sidoruk-sv** [comment]
Any progress on this?

Slightly annoying warning on my project:
> Multiple versions of object-assign found:
>    `4.1.1 ./~/object-assign`
>    `3.0.0 ./~/react-themeable/~/object-assign`

**Comment by JoshuaRogan** [comment]
Same issue as @sidoruk-sv. Would love to see this merged

**Comment by wdh2100** [comment]
Same issue as @sidoruk-sv.

**Comment by HenningThiemann** [comment]
Hi @markdalgleish ,

just checking in. It would be great, if you could merge this PR. The old object-assign version is causing troubles in some of my projects.

**Comment by sidoruk-sv** [comment]
ping

**Pull request closed without merging**
